name: project3
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Tsushko <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  project2:
    path: ../project2
  project1:
    path: ../project1

dev_dependencies:
  test: ^0.12.0
